import type { StudioRenderPlan } from '../convex/lib/studio/renderPlan'
import { writeStudioLocalArtifact } from '../lib/studio/artifact-store'

export type RenderedStudioArtifact = {
  storageKey: string
  thumbnailStorageKey?: string
  fileSizeBytes: number
  mimeType: 'video/mp4'
  width: 1280
  height: 720
  fps: 30
  durationSeconds: number
  aspectRatio: '16:9'
  runtime: 'remotion'
}

const FAKE_MP4_BASE64 =
  'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAASkbW9vdgAAAGxtdmhkAAAAAAAAAAAAAAAAAAAD6AAAA+gAAQAAAQAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAA850cmFrAAAAXHRraGQAAAADAAAAAAAAAAAAAAABAAAAAAAAA+gAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAAAABAAAAABQAAAALQAAAAAAAkZWR0cwAAABxlbHN0AAAAAAAAAAEAAAPoAAAEAAABAAAAAANGbWRpYQAAACBtZGhkAAAAAAAAAAAAAAAAAAA8AAAAPABVxAAAAAAALWhkbHIAAAAAAAAAAHZpZGUAAAAAAAAAAAAAAABWaWRlb0hhbmRsZXIAAAAC8W1pbmYAAAAUdm1oZAAAAAEAAAAAAAAAAAAAACRkaW5mAAAAHGRyZWYAAAAAAAAAAQAAAAx1cmwgAAAAAQAAArFzdGJsAAAAwXN0c2QAAAAAAAAAAQAAALFhdmMxAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAABQAC0ABIAAAASAAAAAAAAAABFUxhdmM2Mi4yOC4xMDIgbGlieDI2NAAAAAAAAAAAAAAAGP//AAAAN2F2Y0MBZAAf/+EAGmdkAB+s2UBQBbsBEAAAAwAQAAADA8DxgxlgAQAGaOvjyyLA/fj4AAAAABBwYXNwAAAAAQAAAAEAAAAUYnRydAAAAAAAAEA4AAAAAAAAABhzdHRzAAAAAAAAAAEAAAAeAAACAAAAABRzdHNzAAAAAAAAAAEAAAABAAABAGN0dHMAAAAAAAAAHgAAAAEAAAQAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAKAAAAAAEAAAQAAAAAAQAAAAAAAAABAAACAAAAAAEAAAoAAAAAAQAABAAAAAABAAAAAAAAAAEAAAIAAAAAAQAACgAAAAABAAAEAAAAAAEAAAAAAAAAAQAAAgAAAAABAAAEAAAAABxzdHNjAAAAAAAAAAEAAAABAAAAHgAAAAEAAACMc3RzegAAAAAAAAAAAAAAHgAAA4oAAAAoAAAAJQAAACUAAAAlAAAALgAAACcAAAAlAAAAJQAAAC4AAAAnAAAAJQAAACUAAAAuAAAAJwAAACUAAAAlAAAALgAAACcAAAAlAAAAJQAAAC4AAAAnAAAAJQAAACUAAAAtAAAAJwAAACUAAAAlAAAALQAAABRzdGNvAAAAAAAAAAEAAATUAAAAYnVkdGEAAABabWV0YQAAAAAAAAAhaGRscgAAAAAAAAAAbWRpcmFwcGwAAAAAAAAAAAAAAAAtaWxzdAAAACWpdG9vAAAAHWRhdGEAAAABAAAAAExhdmY2Mi4xMi4xMDIAAAAIZnJlZQAACA9tZGF0AAACrwYF//+r3EXpvebZSLeWLNgg2SPu73gyNjQgLSBjb3JlIDE2NSByMzIyMiBiMzU2MDVhIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAtIGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTEgcmVmPTMgZGVibG9jaz0xOjA6MCBhbmFseXNlPTB4MzoweDExMyBtZT1oZXggc3VibWU9NyBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0xIG1lX3JhbmdlPTE2IGNocm9tYV9tZT0xIHRyZWxsaXM9MSA4eDhkY3Q9MSBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29mZnNldD0tMiB0aHJlYWRzPTIxIGxvb2thaGVhZF90aHJlYWRzPTMgc2xpY2VkX3RocmVhZHM9MCBucj0wIGRlY2ltYXRlPTEgaW50ZXJsYWNlZD0wIGJsdXJheV9jb21wYXQ9MCBjb25zdHJhaW5lZF9pbnRyYT0wIGJmcmFtZXM9MyBiX3B5cmFtaWQ9MiBiX2FkYXB0PTEgYl9iaWFzPTAgZGlyZWN0PTEgd2VpZ2h0Yj0xIG9wZW5fZ29wPTAgd2VpZ2h0cD0yIGtleWludD0yNTAga2V5aW50X21pbj0yNSBzY2VuZWN1dD00MCBpbnRyYV9yZWZyZXNoPTAgcmNfbG9va2FoZWFkPTQwIHJjPWNyZiBtYnRyZWU9MSBjcmY9MjMuMCBxY29tcD0wLjYwIHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0xOjEuMDAAgAAAANNliIQAN//+9vD+BTZWBFCXEc3onTMfvxW4ujQ3vc4AAAMAAAMAAAMAAAMAHwLMvHs7KdkvDAAAAwAAAwGpAAGRAAKGAAWsABHwADuAAQgABZAAI4AAvgAF4AAiAAEQAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAQFAAAAJEGaJGxDf/6nhAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAwIAAAACFBnkJ4hX8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuEAAAAhAZ5hdEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKgAAAAIQGeY2pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoQAAACpBmmhJqEFomUwIb//+p4QAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAMCEAAAAjQZ6GRREsK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuEAAAAhAZ6ldEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKhAAAAIQGep2pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoAAAACpBmqxJqEFsmUwIb//+p4QAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAMCAAAAAjQZ7KRRUsK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuEAAAAhAZ7pdEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKgAAAAIQGe62pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoAAAACpBmvBJqEFsmUwIb//+p4QAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAMCEAAAAjQZ8ORRUsK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuEAAAAhAZ8tdEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKhAAAAIQGfL2pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoAAAACpBmzRJqEFsmUwIb//+p4QAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAMCAAAAAjQZ9SRRUsK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuEAAAAhAZ9xdEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKgAAAAIQGfc2pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoAAAACpBm3hJqEFsmUwIZ//+nhAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAu4EAAAAjQZ+WRRUsK/8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAJuAAAAAhAZ+1dEJ/AAADAAADAAADAAADAAADAAADAAADAAADADKhAAAAIQGft2pCfwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAyoQAAAClBm7xJqEFsmUwIV//+OEAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMC2gAAACNBn9pFFSwr/wAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAm4QAAACEBn/l0Qn8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAMqAAAAAhAZ/7akJ/AAADAAADAAADAAADAAADAAADAAADAAADADKhAAAAKUGb/UmoQWyZTAhP//3xAAADAAADAAADAAADAAADAAADAAADAAADAAb1'

const FAKE_MP4_BYTES = Uint8Array.from(Buffer.from(FAKE_MP4_BASE64, 'base64'))

const FAKE_JPEG_BYTES = Uint8Array.from([0xff, 0xd8, 0xff, 0xd9])

async function createFakeStudioArtifact(
  jobId: string,
  plan: StudioRenderPlan,
): Promise<RenderedStudioArtifact> {
  const shouldFailThumbnail = process.env.STUDIO_FAKE_RENDER_THUMBNAIL_MODE === 'fail'
  const storageKey = `studio/${jobId}/artifact.mp4`
  const thumbnailStorageKey = shouldFailThumbnail
    ? undefined
    : `studio/${jobId}/artifact-thumbnail.jpg`

  await writeStudioLocalArtifact({
    storageKey,
    bytes: FAKE_MP4_BYTES,
  })

  if (thumbnailStorageKey) {
    await writeStudioLocalArtifact({
      storageKey: thumbnailStorageKey,
      bytes: FAKE_JPEG_BYTES,
    })
  }

  return {
    storageKey,
    thumbnailStorageKey,
    fileSizeBytes: FAKE_MP4_BYTES.byteLength,
    mimeType: 'video/mp4',
    width: plan.output.width,
    height: plan.output.height,
    fps: plan.output.fps,
    durationSeconds: plan.output.durationSeconds,
    aspectRatio: plan.output.aspectRatio,
    runtime: plan.runtime,
  }
}

export async function renderStudioArtifact(
  jobId: string,
  plan: StudioRenderPlan,
): Promise<RenderedStudioArtifact> {
  const renderMode = process.env.STUDIO_RENDER_MODE ?? 'fake'

  if (renderMode === 'fake') {
    if (process.env.NODE_ENV === 'production') {
      throw new Error(
        'RENDER_FAILED: STUDIO_RENDER_MODE=fake is disabled in production.',
      )
    }
    return createFakeStudioArtifact(jobId, plan)
  }

  if (renderMode === 'remotion') {
    throw new Error(
      'RENDER_FAILED: STUDIO_RENDER_MODE=remotion is reserved until the Remotion renderer command is wired.',
    )
  }

  throw new Error(`RENDER_FAILED: Unsupported STUDIO_RENDER_MODE "${renderMode}".`)
}
