/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RemotionIndexRouteImport } from './routes/remotion/index'
import { Route as HyperframesIndexRouteImport } from './routes/hyperframes/index'
import { Route as RemotionOwnerSlugRouteImport } from './routes/remotion/$owner.$slug'
import { Route as HyperframesOwnerSlugRouteImport } from './routes/hyperframes/$owner.$slug'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotionIndexRoute = RemotionIndexRouteImport.update({
  id: '/remotion/',
  path: '/remotion/',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperframesIndexRoute = HyperframesIndexRouteImport.update({
  id: '/hyperframes/',
  path: '/hyperframes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RemotionOwnerSlugRoute = RemotionOwnerSlugRouteImport.update({
  id: '/remotion/$owner/$slug',
  path: '/remotion/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HyperframesOwnerSlugRoute = HyperframesOwnerSlugRouteImport.update({
  id: '/hyperframes/$owner/$slug',
  path: '/hyperframes/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hyperframes/': typeof HyperframesIndexRoute
  '/remotion/': typeof RemotionIndexRoute
  '/hyperframes/$owner/$slug': typeof HyperframesOwnerSlugRoute
  '/remotion/$owner/$slug': typeof RemotionOwnerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hyperframes': typeof HyperframesIndexRoute
  '/remotion': typeof RemotionIndexRoute
  '/hyperframes/$owner/$slug': typeof HyperframesOwnerSlugRoute
  '/remotion/$owner/$slug': typeof RemotionOwnerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hyperframes/': typeof HyperframesIndexRoute
  '/remotion/': typeof RemotionIndexRoute
  '/hyperframes/$owner/$slug': typeof HyperframesOwnerSlugRoute
  '/remotion/$owner/$slug': typeof RemotionOwnerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/hyperframes/'
    | '/remotion/'
    | '/hyperframes/$owner/$slug'
    | '/remotion/$owner/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/hyperframes'
    | '/remotion'
    | '/hyperframes/$owner/$slug'
    | '/remotion/$owner/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/hyperframes/'
    | '/remotion/'
    | '/hyperframes/$owner/$slug'
    | '/remotion/$owner/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HyperframesIndexRoute: typeof HyperframesIndexRoute
  RemotionIndexRoute: typeof RemotionIndexRoute
  HyperframesOwnerSlugRoute: typeof HyperframesOwnerSlugRoute
  RemotionOwnerSlugRoute: typeof RemotionOwnerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotion/': {
      id: '/remotion/'
      path: '/remotion'
      fullPath: '/remotion/'
      preLoaderRoute: typeof RemotionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperframes/': {
      id: '/hyperframes/'
      path: '/hyperframes'
      fullPath: '/hyperframes/'
      preLoaderRoute: typeof HyperframesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remotion/$owner/$slug': {
      id: '/remotion/$owner/$slug'
      path: '/remotion/$owner/$slug'
      fullPath: '/remotion/$owner/$slug'
      preLoaderRoute: typeof RemotionOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hyperframes/$owner/$slug': {
      id: '/hyperframes/$owner/$slug'
      path: '/hyperframes/$owner/$slug'
      fullPath: '/hyperframes/$owner/$slug'
      preLoaderRoute: typeof HyperframesOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HyperframesIndexRoute: HyperframesIndexRoute,
  RemotionIndexRoute: RemotionIndexRoute,
  HyperframesOwnerSlugRoute: HyperframesOwnerSlugRoute,
  RemotionOwnerSlugRoute: RemotionOwnerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
